export { default as Home } from './Home'
export { default as Disease } from './Disease'
export { default as Prediction } from './Prediction'
export { default as History } from './History'
export { default as About } from './About'